//#define  FILE_CREATELIST_  FILE_CREATELIST64_	
#define  LOCKFILE  FILE_LOCKFILE64_
#define  LOCKREC FILE_LOCKREC64_
#define  READX FILE_READ64_
#define  READLOCKX  FILE_READLOCK64_
#define  READUPDATEX FILE_READUPDATE64_
#define  READUPDATELOCKX FILE_READUPDATELOCK64_
//#define  SETMODENOWAIT FILE_SETMODENOWAIT64_
#define  UNLOCKFILE FILE_UNLOCKFILE64_
#define  WRITEX FILE_WRITE64_
#define  WRITEUPDATEX 	FILE_WRITEUPDATE64_
#define  WRITEUPDATEUNLOCKX FILE_WRITEUPDATEUNLOCK64_
//#define  WRITEREADX FILE_WRITEREAD64_

